create table if not exists public.content_items (
  id text primary key,
  source_id text not null,
  source_name text not null,
  source_url text not null,
  source_title text not null,
  source_fingerprint text not null unique,
  raw_excerpt text not null default '',
  status text not null check (
    status in (
      'collected',
      'draft_created',
      'pending_review',
      'approved',
      'rejected',
      'channel_generated',
      'publish_pending',
      'published',
      'failed'
    )
  ),
  draft_title text not null default '',
  draft_body text not null default '',
  review_message_id text not null default '',
  review_requested_at timestamptz,
  review_decision_at timestamptz,
  rejection_reason text not null default '',
  notion_page_id text not null default '',
  notion_synced_at timestamptz,
  attempt_count integer not null default 0,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.channel_outputs (
  id text primary key,
  content_item_id text not null references public.content_items(id) on delete cascade,
  channel_id text not null,
  status text not null check (
    status in (
      'generated',
      'publish_pending',
      'published',
      'failed'
    )
  ),
  payload_json jsonb not null default '{}'::jsonb,
  artifact_path text not null default '',
  published_url text not null default '',
  attempt_count integer not null default 0,
  next_retry_at timestamptz,
  locked_until timestamptz,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (content_item_id, channel_id)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  content_item_id text references public.content_items(id) on delete set null,
  event_type text not null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_content_items_status
  on public.content_items(status);

create index if not exists idx_channel_outputs_status
  on public.channel_outputs(status);

create index if not exists idx_channel_outputs_publish_queue
  on public.channel_outputs(status, next_retry_at, locked_until);

create index if not exists idx_events_content_item_id
  on public.events(content_item_id);

alter table public.content_items enable row level security;
alter table public.channel_outputs enable row level security;
alter table public.events enable row level security;
