/**
 * Builds the channel-specific prompt used after human approval of the master draft.
 */
export function buildInstagramChannelPrompt({ brand, item, channel }) {
  const ctaEnabled = Boolean(brand.cta?.enabled && brand.cta?.url);

  return {
    system: [
      'You adapt an approved Korean master marketing draft into Instagram card-news content.',
      '',
      'The master draft has already been reviewed by a human. Do not change the main claim or invent new facts.',
      'Your job is channel-specific adaptation: clearer slide sequencing, shorter card copy, Instagram caption, and hashtags.',
      '',
      'Write Korean copy for small business owners, one-person businesses, and side-business operators.',
      'Use a clear, practical, founder-friendly tone.',
      'Avoid hype, vague motivation, and generic branding cliches.',
      '',
      'Return exactly five slides.',
      'Each slide should be concise enough for a 1080x1080 card-news layout.',
      'Prefer short, strong headlines and practical body copy.',
      '',
      ctaEnabled
        ? 'A CTA URL is configured. The final slide may use a soft CTA and the caption may include the CTA.'
        : 'No CTA URL is configured. Do not mention open chat, QR, link in bio, consultation link, or any sample URL.',
      '',
      'Return JSON only.'
    ].join('\n'),
    user: [
      `Company: ${brand.companyName}`,
      `Brand voice: ${brand.brandVoice}`,
      `Service summary: ${brand.serviceSummary}`,
      `CTA enabled: ${ctaEnabled ? 'true' : 'false'}`,
      `CTA label: ${ctaEnabled ? brand.cta?.label || '' : ''}`,
      `CTA URL: ${ctaEnabled ? brand.cta?.url || '' : ''}`,
      'Channel:',
      `- ID: ${channel.id}`,
      `- Format: ${channel.format}`,
      `- Template: ${channel.template}`,
      '',
      'Source:',
      `- Title: ${item.source_title}`,
      `- URL: ${item.source_url}`,
      '',
      'Approved master draft:',
      `- Title: ${item.draft_title}`,
      `- Body: ${item.draft_body}`,
      '',
      'Create Instagram card-news content that matches this JSON schema:',
      '{',
      '  "slides": [',
      '    { "role": "hook", "label": "", "headline": "", "body": "", "emphasis": "" },',
      '    { "role": "problem", "label": "", "headline": "", "body": "", "emphasis": "" },',
      '    { "role": "insight", "label": "", "headline": "", "body": "", "emphasis": "" },',
      '    { "role": "solution", "label": "", "headline": "", "body": "", "emphasis": "" },',
      '    { "role": "closing", "label": "", "headline": "", "body": "", "emphasis": "" }',
      '  ],',
      '  "caption": "",',
      '  "hashtags": [],',
      '  "visual_notes": ""',
      '}'
    ].join('\n')
  };
}

const sketchCoverImagePromptGuidance = [
  '커버 이미지 프롬프트 요구사항:',
  '- cover_image_prompt는 세로 4:5 인스타그램 첫 카드 배경용 이미지 생성 프롬프트여야 한다.',
  '- 이 이미지는 인스타그램 카드뉴스 게시물의 첫 번째 카드에 사용된다.',
  '- 이 이미지는 이후 한국어 HTML 제목 텍스트가 위에 올라가는 배경으로 사용된다.',
  '',
  '본문 우선 규칙:',
  '- 먼저 승인된 마스터 초안에서 핵심 비즈니스 상황, 고객의 긴장감, 또는 전략적 인사이트를 파악한다.',
  '- 이미지는 특정 브랜드 캐릭터를 먼저 보여주는 것이 아니라, 승인된 초안의 내용을 먼저 시각화해야 한다.',
  '- 그다음 초안의 분위기와 메시지에 어울리는 의인화된 동물 캐릭터를 장면 안에 자연스럽게 배치한다.',
  '- 이미지 콘셉트는 이 승인된 마스터 초안에 분명히 속한다고 느껴질 만큼 구체적이어야 한다.',
  '- 어떤 글에도 어울릴 수 있는 재사용 가능한 동물 캐릭터 이미지를 만들지 않는다.',
  '',
    '의인화된 동물 캐릭터 사용 규칙:',
  '- 장면에는 초안의 핵심 메시지에 어울리는 의인화된 동물 캐릭터가 등장할 수 있다.',
  '- 동물은 고정하지 않는다. 초안의 내용, 감정, 상황에 맞춰 가장 적절한 동물을 선택한다.',
  '- 동물 캐릭터는 귀여운 마스코트가 아니라, 상황에 맞는 모습이어야 한다.',
  '- 초안의 내용에 따라 동물의 역할, 행동, 도구, 환경을 바꾼다.',
  '- 동물은 탐정, 건축가, 편집자, 안내자, 지도 제작자, 수리공, 큐레이터, 신호 해석가, 매장 조언자, 사서, 분석가, 장인, 상담자처럼 행동할 수 있다.',
  '- 유치한 표정, 과장된 감정 표현, 캐릭터 상품 같은 포즈, 어린이 그림책 같은 귀여움은 피한다.',
  '',
  '시각적 은유 규칙:',
  '- 초안의 핵심 메시지를 나타내는 하나의 명확한 은유적 장면을 만든다.',
  '- 은유는 일반적인 마케팅 이미지가 아니라 초안의 의미에서 나와야 한다.',
  '- 추상적인 상징보다 구체적인 비즈니스, 고객, 브랜드 상황을 우선한다.',
  '- 장면은 특정한 상황, 긴장감, 또는 변화 과정을 보여줘야 한다.',
  '- 좋은 은유 방향의 예시는 다음과 같다: 불명확한 고객 경로, 혼란스러운 매장 전면, 어지러운 메시지 시스템, 신뢰의 다리, 신호 제어실, 고장 난 간판, 고객 질문 지도, 브랜드 수리 작업대, 비교 진열대, 기록 보관실, 패키징 테이블, 갤러리 월 등. 단, 초안 내용과 관련 있을 때만 사용한다.',
  '',
  '- 왼쪽 아래 영역에는 제목이 들어갈 영역으로 그 영역에 중요한 요소를 배치하지 않는다.',
  '장면 다양화:',
  '- 명확한 배경을 가진 하나의 구체적인 장면을 묘사한다.',
  '- 승인된 초안의 실제 의미를 반영하는 사물, 배경, 행동을 사용한다.',
  '- 결과물은 초안을 시각적으로 해석한 이미지처럼 느껴져야 한다.',
  '',
  '스타일:',
  '- 브랜드 전략 인스타그램 커버에 어울리는 에디토리얼 일러스트레이션.',
  '- 굵은 외곽선, 명확한 형태, 강한 대비, 포스터 같은 구성을 사용한다.',
  '- 따뜻하지만 날카로운 브랜드 인사이트 분위기.',
  '- 이미지는 그래픽 노블 에디토리얼 패널, 빈티지 비즈니스 포스터, 현대적인 컷페이퍼 에디토리얼 일러스트, 잉크 앤 마커 전략 스케치, 강렬한 매거진 커버 일러스트 느낌 중 초안의 메시지에 가장 잘 맞는 방향을 선택할 수 있다.',
  '- 초안의 메시지에 가장 잘 맞는 시각적 표현 방식을 선택한다.',
  '- 부드러운 동화책 스케치, 유치한 귀여움, 포토리얼리즘, 3D, 애니메이션풍, 사이버펑크, 기업용 스톡 일러스트 느낌은 피한다.',
  '',
  '색상:',
  '- 아이보리 또는 크림색 계열의 기본 배경을 사용한다.',
  '- 검정 또는 차콜을 주요 구조 색상으로 사용한다.',
  '- 초안의 분위기에 맞는 하나의 주요 포인트 색상을 선택한다: 딥그린, 웜브라운, 차분한 오렌지, 더스티 블루, 올리브, 버건디.',
  '- 아주 작은 라임색 GrowthLine 포인트를 포함할 수 있지만, 이미지에서 지배적으로 보이면 안 된다.',
  '',
  '구성:',
  '- 세로 4:5 인스타그램 첫 카드 배경으로 디자인한다.',
  '- 큰 한국어 HTML 제목 오버레이가 올라갈 수 있도록 좌하단 영역은 비교적 단순하고 읽기 쉽게 유지한다.',
  '- 작은 브랜드명 오버레이가 올라갈 수 있도록 우상단 영역은 단순하게 유지한다.',
  '- 의인화된 동물 캐릭터의 얼굴, 몸, 핵심 오브젝트는 좌하단 제목 영역과 충돌하지 않도록 중앙, 오른쪽, 또는 상단 영역에 배치한다.',
  '- 좌하단 영역은 비어 보이면 안 되지만, 한국어 제목 텍스트가 올라가도 잘 읽힐 만큼 단순해야 한다.',
  '- 필요할 경우 카메라 앵글을 다양하게 사용한다: 클로즈업, 탑뷰, 측면 시점, 넓은 장면, 포스터형 중앙 구도.',
  '',
  '엄격한 금지 규칙:',
  '- 이미지 안에는 텍스트를 넣지 않는다.',
  '- 한국어, 영어, 숫자, 로고, 워터마크, 간판, 말풍선, 읽을 수 있는 문서, UI 화면, 텍스트 차트, 타이포그래피를 넣지 않는다.',
  '- 가짜 인터페이스 화면이나 읽을 수 있는 마케팅 자료를 포함하지 않는다.',
  '',
  '출력 규칙:',
  '- cover_image_prompt는 완성된 이미지 생성 프롬프트여야 한다.',
  '- cover_image_prompt 안에서 콘셉트를 따로 설명하지 않는다.',
  '- 여러 개의 선택지를 포함하지 않는다.',
  '- 이미지가 초안을 기반으로 한다고 언급하지 않는다.',
  '- 이미지 생성 API에 바로 보낼 수 있는 하나의 구체적인 이미지 프롬프트를 작성한다.'
].join('\n');

const sketchTextFitGuidance = [
  'Text fit rules for the 1080x1350 sketch template:',
  '- Treat these limits as rendering budgets, not writing suggestions.',
  '- Count Korean syllables, English letters, and numbers as visible characters. Ignore spaces and line breaks when estimating length.',
  '- Prefer 2 short title lines over 1 long title line. Do not create 4-line titles.',
  '- If a card needs more detail than the budget allows, shorten the copy or split the idea into another useful card.',
  '- Do not repeat section labels inside body text. The label fields already render labels such as Problem, Solution, Before, and After.',
  '- Keep body copy as short lines that can be rendered directly with the line breaks you return.',
  '',
  'Layout 01 Cover:',
  '- kicker: up to 18 visible characters.',
  '- title: up to 3 lines, about 30 visible characters total, and no line longer than 13 visible characters.',
  '- subtitle: up to 3 short lines, about 36 visible characters total.',
  '',
  'Layout 02 Q&A:',
  '- question: up to 2 lines and about 28 visible characters total.',
  '- answer: 3 to 5 short lines, about 90 visible characters total.',
  '',
  'Layout 03 Problem / Solution:',
  '- title: up to 2 lines and about 26 visible characters total.',
  '- problem: 3 to 6 short lines, about 55 visible characters total.',
  '- solution: 3 to 6 short lines, about 65 visible characters total.',
  '- Use compact contrast. Do not write paragraph-style explanations.',
  '',
  'Layout 04 Customer Flow:',
  '- title: up to 2 lines and about 26 visible characters total.',
  '- each step title: up to 10 visible characters.',
  '- each step description: 1 to 2 short lines.',
  '',
  'Layout 05 Checklist and Layout 08 Summary:',
  '- title: up to 2 lines and about 24 visible characters total.',
  '- each item: 1 to 2 short lines, about 24 visible characters total.',
  '',
  'Layout 06 Before / After:',
  '- title: up to 2 lines and about 24 visible characters total.',
  '- before: 3 to 5 short lines, about 55 visible characters total.',
  '- after: 3 to 6 short lines, about 65 visible characters total.',
  '- Prefer contrast pairs over dense explanation.',
  '',
  'Layout 07 One Message and Layout 09 Closing:',
  '- title: up to 2 lines and about 30 visible characters total.',
  '- description or cta: 2 to 4 short lines.'
].join('\n');

/**
 * Builds the prompt for the GrowthLine sketch-note Instagram template.
 */
export function buildInstagramSketchCardNewsPrompt({ config = {}, brand, item, channel }) {
  const ctaEnabled = Boolean(brand.cta?.enabled && brand.cta?.url);
  const staticFinalCtaEnabled = Boolean(config.instagramFinalCtaImagePath);

  return {
    system: [
      `너는 ${brand.companyName || 'GrowthLine'}의 인스타그램 카드뉴스 콘텐츠 에디터다.`,
      '',
      `${brand.companyName || 'GrowthLine'}은 온라인 채널이 약한 기업이 온라인에서 고객을 이해시키고, 신뢰를 만들고, 문의와 매출로 이어지도록 돕는 브랜드다.`,
      '콘텐츠 톤은 "마케팅 강의자료"가 아니라 "브랜드 전략가가 직접 정리한 스케치 노트"처럼 보여야 한다.',
      '',
      '작성 원칙은 다음과 같다.',
      '1. 텍스트는 한국어로 작성한다.',
      '2. 너무 AI가 쓴 것처럼 보이는 표현을 피한다.',
      '3. 과장된 문구, 뻔한 마케팅 문장, 과도한 이모지, 과도한 해시태그는 사용하지 않는다.',
      '4. 문장은 짧고 명확하게 쓴다.',
      '5. 독자가 "맞아, 이거 우리 문제다"라고 느끼도록 구체적으로 쓴다.',
      '6. 단순 정보 요약이 아니라 인스타그램 카드뉴스 흐름으로 재구성한다.',
      '7. 첫 장 이미지는 별도 생성 또는 별도 제공될 수 있으므로 카드 텍스트와 이미지 프롬프트를 분리한다.',
      '8. 출력은 반드시 JSON 형식으로만 한다.',
      '9. 각 카드의 텍스트는 HTML에 바로 넣기 좋게 줄바꿈 위치를 포함한다.',
      '10. 각 문장은 너무 길지 않게 유지하고, 한 카드에 너무 많은 정보를 넣지 않는다.',
      '',
      '사용 가능한 레이아웃은 다음과 같다.',
      '',
      'LAYOUT 01. Cover',
      '- 첫 장 이미지 백그라운드 위에 올릴 텍스트용이다.',
      '- 콘텐츠 전체를 관통하는 강한 제목, 짧은 부제, 시리즈명을 작성한다.',
      '- 이미지는 직접 만들지 말고 cover_image_prompt에 이미지 생성 프롬프트만 작성한다.',
      '',
      sketchCoverImagePromptGuidance,
      '',
      sketchTextFitGuidance,
      '',
      'LAYOUT 02. Q&A',
      '- 독자가 실제로 궁금해할 질문이 있을 때 사용한다.',
      '- "~해야 할까요?", "왜 ~일까요?"처럼 질문으로 시작하기 좋다.',
      '',
      'LAYOUT 03. Problem / Solution',
      '- 문제와 해결 방향이 명확할 때 사용한다.',
      '- 현재 고객이나 브랜드가 겪는 문제를 먼저 보여주고, 그에 대한 해결 방향을 제시한다.',
      '',
      'LAYOUT 04. Customer Flow',
      '- 고객 행동의 순서, 설득의 흐름, 전환 구조를 설명할 때 사용한다.',
      '- 3단계 흐름으로 작성한다.',
      '',
      'LAYOUT 05. Checklist',
      '- 실무자가 바로 점검할 수 있는 항목이 필요할 때 사용한다.',
      '- 4개 체크 항목으로 작성한다.',
      '',
      'LAYOUT 06. Before / After',
      '- 기존 방식과 개선 방식을 비교할 때 사용한다.',
      '- Before는 흔한 실수, After는 더 나은 접근으로 작성한다.',
      '',
      'LAYOUT 07. One Message',
      '- 가장 중요한 핵심 문장을 강하게 보여줄 때 사용한다.',
      '- 한 문장 중심으로 묵직하게 작성한다.',
      '',
      'LAYOUT 08. Summary',
      '- 앞 내용을 4개 포인트로 정리할 때 사용한다.',
      '- 각 항목은 짧고 기억하기 쉽게 작성한다.',
      '',
      'LAYOUT 09. Closing',
      '- 마지막 장에서 결론과 저장 유도 문구를 작성한다.',
      '- 과한 판매 CTA가 아니라, 저장하거나 다시 보게 만드는 문장으로 마무리한다.',
      '',
      '카드 구성 규칙:',
      '- Cover와 Closing은 반드시 포함한다.',
      '- Cover는 첫 번째 카드여야 한다.',
      '- Closing은 마지막 카드여야 한다.',
      '- 전체 카드는 최소 2장, 최대 8장이다.',
      '- 2~8번 레이아웃 중 내용에 필요 없는 것은 제외한다.',
      '- recommended_layout_flow는 실제 cards 순서와 일치해야 한다.',
      '',
      ctaEnabled
        ? 'CTA URL이 설정되어 있다. 마지막 장과 caption에는 과하지 않은 CTA를 사용할 수 있다.'
        : 'CTA URL이 설정되어 있지 않다. 오픈채팅, QR, 링크, 상담 링크, 샘플 URL을 언급하지 않는다.',
      '',
      'Return JSON only.'
    ].join('\n'),
    user: [
      `Company: ${brand.companyName}`,
      `Brand voice: ${brand.brandVoice}`,
      `Service summary: ${brand.serviceSummary}`,
      `CTA enabled: ${ctaEnabled ? 'true' : 'false'}`,
      `CTA label: ${ctaEnabled ? brand.cta?.label || '' : ''}`,
      `CTA URL: ${ctaEnabled ? brand.cta?.url || '' : ''}`,
      '',
      'Channel:',
      `- ID: ${channel.id}`,
      `- Format: ${channel.format}`,
      `- Template: ${channel.template}`,
      '',
      'Source:',
      `- Title: ${item.source_title}`,
      `- URL: ${item.source_url}`,
      '',
      'Approved master draft:',
      `- Title: ${item.draft_title}`,
      `- Body: ${item.draft_body}`,
      '',
      `Static final CTA image enabled: ${staticFinalCtaEnabled ? 'true' : 'false'}`,
      staticFinalCtaEnabled
        ? 'When static final CTA image is enabled, keep the normal 2 to 8 card flow. The final Closing card visual will be replaced by the static CTA image during rendering, so use Closing only as metadata.'
        : 'When static final CTA image is disabled, return 2 to 8 cards and omit optional middle layouts that are not useful.',
      '',
      'Create Instagram sketch card-news content that matches the JSON schema. Include cover_image_prompt for the thumbnail/background image, but do not place image instructions inside card text.',
      'Before returning JSON, apply the text fit rules from the system prompt. If any card exceeds the budget, shorten it or split the idea into another useful card.'
    ].join('\n')
  };
}
